version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: food_bot_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 7y57ZlDyf3
      MYSQL_DATABASE: mhatefi1_food_bot_db
    ports:
      - "3307:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d